
# ===== Build stage of application =====
FROM golang:1.21-alpine3.18 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY slimdough/dist ./dist

RUN go build -v -o /pork-go

# ===== Deploy app bin into a lean image =====
#FROM alpine:3.18 AS build-release-stage
#
#WORKDIR /
#
#COPY --from=build-stage /dist /dist
#COPY --from=build-stage /pork-go /pork-go
#
#EXPOSE 8000
#
#CMD ["/pork-go"]
