ALTER TABLE "PointsOnPost" DROP CONSTRAINT IF EXISTS UC_User_Post;

ALTER TABLE "PointsOnPost" ADD CONSTRAINT UC_User_Post UNIQUE (UserId, PostId);

ALTER TABLE "UserPost"
ADD isDeleted BOOLEAN DEFAULT FALSE;
