databaseType = "PostgreSql"
name = "flyway"
id = "3f862b32-4f88-42ce-bc88-893be4522c65"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[flyway]
mixed = true
outOfOrder = true
validateMigrationNaming = true
locations = [ "filesystem:migrations" ]

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgres.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.default]
url = "jdbc:postgresql://localhost:5432/knostash_db"
schemas = [ "public" ]
displayName = "knostash_user"
user = "knostash_user"
password = "example"

[environments.DigitalOceanDroplet]
url = "jdbc:postgresql://159.203.169.44:5432/satch3l"
schemas = [ "public" ]
displayName = "wthunder"

[environments.Local]
url = "jdbc:postgresql://localhost:5432/knostash_db"
schemas = [ "public" ]
